name: Bolt from the Blue Copywriting
favicon: null
layout_spectrum: 1
typography_spectrum: 0.44591
title: Bolt from the Blue Copywriting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#22e3f9'
    - '#000000'
    - '#979797'
    - '#dbdbdb'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
