name: Bolt from the Blue Copywriting
favicon: null
layout_spectrum: 1
typography_spectrum: 0.44591
title: Bolt from the Blue Copywriting
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#22e3f9'
    - '#000000'
    - '#979797'
    - '#dbdbdb'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
